import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Navbar from './components/nav-bar';
import { Suspense } from 'react';
import { Analytics } from '@vercel/analytics/react';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Media Tracker',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} flex lg:flex-row flex-col antialiased h-screen w-full`}>
				<Navbar />
				<Suspense>
					<main className="w-full h-fit lg:ml-48 mt-16 lg:mt-0 p-4">{children}</main>
				</Suspense>
				<Analytics />
			</body>
		</html>
	);
}
